name: supreme
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6.13
  - numpy=1.19.2
  - cpuonly=2.0
  - pytorch=1.10.2
  - pytorch-mutex=1.0=cpu
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - rpy2==3.4.5

  - pip  # conda installer for pip; versions sotto in sezione pip
  - pip:
      - pandas==1.1.5
      - pickle5==0.0.12
      - pip==21.3.1
      - python-dateutil==2.8.2
      - scikit-learn==0.24.2
      - torch-geometric==2.0.3
      - torch-scatter==2.0.9
      - torch-sparse==0.6.12
      - xgboost==1.5.2