project:
  seed: 2025
  split_seed: 42
  experiment_name: "pancan_gnn_experiment_001"
  device: "cuda"   # Opzioni: "cuda" o "cpu"
paths:
  training_data_dir: "./data/training"
  results_dir: "./results/pancan"
  models_dir: "./models/pancan"
  logs_dir: "./logs/pancan"
  figures_dir: "./figures/pancan"
  external_data_dir: "./data/external"
  raw_data_dir: "./data/pancan_tcga/raw"
pancan_paths:
  #expression_variance_path: "expression_variance.tsv"
  expression_variance_path: "expression_fvalues.tsv"
  expression_path: "expression_data_pancan.tsv"
  cnv_path: "cnv_data_pancan.tsv"
  mirna_path: "mirna_data_top_100.tsv"
  clinical_data_path: "molecular_subtype.csv"
  adj_path: "adj_matrix_biogrid.npz"
  mirna_gene_matrix_path: "standardized_mirna_mrna_edge_filtered_at_eight_with_top_100_mirna.npz"
  tf_gene_matrix_path: "tf_gene_adj_global.npz"
  tf_nodes_path: "tf_nodes_all_in_vocab.csv"
brca_paths:
  #expression_variance_path: "expression_variance.tsv"
  expression_variance_path: "expression_fvalues.tsv"
  expression_path: "expression_data_brca.tsv"
  cnv_path: "brca_cnv_data.tsv"
  mirna_path: "brca_mirna_data_top_100.tsv"
  clinical_data_path: "brca_molecular_subtype.csv"
  adj_path: "brca_adj_matrix_biogrid.npz"
  mirna_gene_matrix_path: "brca_standardized_mirna_mrna_edge_filtered_at_eight_with_top_100_mirna.npz"
data:
  num_gene: 700
  num_mirna: 100
  omic_mode: 4
  batch_size: 16
  num_workers: 1
  gene_gene: True
  mirna_gene: True
  mirna_mirna: True
  tf_gene: False
  tf_tf: False
  tf_mirna: False
  num_tf: 0
  feature_selection_method: variance   # Opzioni: "variance", "GSP", "community", null
  normalization: min-max               # Opzioni: "min-max", "mad", "z-score". Fit solo su training set.
model:
  name: "gat_tf"             # Opzioni supportate: "gat", "gatv2", "gcn", "baseline"
  parallel: true         # Se true, aggiunge un ramo fully connected parallelo (vedi gat.py)
  poolsize: 8             # Dimensione del pooling (graph_max_pool)
  poolrate: 0.8           # Tasso di pooling (usato in alcune varianti di architetture)
  dropout: 0.6
  jumping_knowledge: false    # Abilita Jumping Knowledge
  jk_mode: "max"            # Modalità di Jumping Knowledge: "cat", "max", "lstm", "sum"
graph:
  edge_weight: true
  edge_attribute: false
train:
  #resume_checkpoint: "results/pancan/pancan_gnn_experiment_001_20260123_192435/checkpoints/best_checkpoint_epoch_19.pth"
  num_epochs: 50
  # Loss e Regolarizzazione
  l2: true                # Attiva la regolarizzazione L2 manuale definita in gat.py
  l2_reg_factor: 0.0005   # Fattore lambda per la L2 regularization
  decoder: true
  learning_rate: 0.01
  weight_decay: 0.0001
  validation_split: 0.2
  shuffle: true
  ce_weighted: false     # Se true, calcola pesi per la CrossEntropy in base alla distribuzione delle classi
early_stopping:
  enabled: true
  patience: 5         # Epoche di attesa prima di fermare
  metric: f1      # Miglioramento minimo richiesto
  strategy: "maximize"  # "minimize" o "maximize" in base alla metrica
optimizer:
  name: "adamw"           # Consigliato AdamW per deep learning moderno
scheduler:
  name: "cosine"          # Opzioni in scheduler.py: "constant", "step", "exponential", "cosine"
  # Nota: i parametri specifici (T_max, gamma) sono hardcoded in scheduler.py, 
  # ma il nome qui seleziona quale usare.
# Parametri per il Sampler (usati in builder.py -> build_data_loader)
sampler_strategy: "random" # Opzioni: "random", "weighted", "none"
sampler_gamma: 0.98         # Fattore di smorzamento per il sampler "weighted", tra 0 e 1. Valori più bassi aumentano la diversità dei campioni.
sampler_mode: "nulite" # Opzioni: "nulite", "alpha"
tuning:
  # Questi parametri possono essere sovrascritti durante l'esecuzione di esperimenti specifici (vedi sweep_config.yml)
  train_fraction: 1.0   # Frazione del set di addestramento da utilizzare (tra 0 e 1). Se <1.0, riduce il numero di campioni usati per l'addestramento.
misc:
  debug: false
wandb:
  enabled: false
  project_name: "multiomics_gnn"
  tags: ["gnn", "multiomics", "tcga", "pancan"]
